# Generated by Django 6.0.4 on 2026-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('mission', models.TextField()),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
